### ISSUE TITLE
Adhere to Stricter Styling Guide

### ISSUE THREAD

**Issue by CrutchTheClutch** [Russelldan554/budget-frontend#26]
Currently, React has a very loose styling guide.  This results in a wide variety of code styling throughout the application.  The aim of this issue is to improve the application's overall code styling by using a much more opinionated style guide such as [Airbnb's React Style Guide](https://github.com/airbnb/javascript/tree/master/react).

**While not necessarily needed, this issue aims to improve readability within the code-base before it grows any larger.**

**Comment by Russelldan554** [comment]
Ill read up on this style guide and keep it in mind
