### ISSUE TITLE
Request failed with status code 400 after Login

### ISSUE THREAD

**Issue by CrutchTheClutch** [Russelldan554/budget-frontend#30]
If a user logs in to the application, they are met with error messages.  These errors are due to requests being sent to the database, before retrieving the users ID:

- ```GET http://localhost:8080/users/null/accounts 400```
- ```GET http://localhost:8080/users/null/budgets 400```
- ```GET http://localhost:8080/users/null/transactions 400```

Once the page is reloaded, these errors do not occur, because the user ID is assigned.

**Example**:

Accounts Before Page Reload
![BeforeExample](https://user-images.githubusercontent.com/22361526/56945240-56e8f300-6adb-11e9-91b0-90d368c0982a.PNG)

Accounts After Page Reload
![AfterExample](https://user-images.githubusercontent.com/22361526/56945241-57818980-6adb-11e9-98d1-3880c26318b6.PNG)

**Comment by Russelldan554** [comment]
Fixed in PR #32
